# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

before_install:
  Rscript -e 'update.packages(ask = FALSE)'
  mv description_for_travisCI DESCRIPTION

r_github_packages: hadley/devtools#1263
